name: fruit_app_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.1.2
  dartz: ^0.10.1
  firebase_core: ^4.1.1
  firebase_storage: ^13.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  image_picker: ^1.2.0
  path: ^1.9.1
  skeletonizer: ^2.1.0+1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
